export const NotificationType = {
    INVITE_RECEIVED: 'INVITE_RECEIVED',
    JOIN_REQUEST_RECEIVED: 'JOIN_REQUEST_RECEIVED',
    JOIN_REQUEST_ACCEPTED: 'JOIN_REQUEST_ACCEPTED',
    JOIN_REQUEST_DECLINED: 'JOIN_REQUEST_DECLINED',
    MEMBER_REMOVED: 'MEMBER_REMOVED',
    OWNERSHIP_TRANSFERRED: 'OWNERSHIP_TRANSFERRED',
    MONTH_CLOSED: 'MONTH_CLOSED',
} as const;

export type NotificationType = (typeof NotificationType)[keyof typeof NotificationType];
